--- 
title: "UVA Health Sciences Library Workshops"
author: "Data Services @ HSL"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This site hosts workshop tutorials for researchers in the life sciences at the University of Virginia to learn R skills."
---

# Getting Started

These tutorials assume that you have downloaded R and RStudio.

-	Download R for [Windows](https://cran.r-project.org/bin/windows/base/) or for [Mac](https://cran.r-project.org/bin/macosx/) (download the latest .pkg file for your OS)
-	Download [RStudio Desktop](https://www.rstudio.com/products/rstudio/download/#download)

R and RStudio are separate downloads and installations. You need R installed before you install RStudio. R is the underlying statistical computing environment, but using R alone is no fun. RStudio is a graphical integrated development environment that makes using R much easier. 

# About the Instructors

The Data Services team at the Health Sciences Library at the University of Virginia proudly hosts in-person workshops throughout the year and hosts personalized consults with UVA faculty, staff, and students to assist them with data analysis.

You can find out more about us at [](https://data.hsl.virginia.edu)

#### David N Martin, MS

David is the Clinical Data Research Specialist at the Health Sciences Library where he consults with clinicians, nurses, and students on data analysis and programming in a number of languages. He is also a PhD candidate in the Curry School of Education researching the impacts of the No Child Left Behind policy.

- Email: dnm5ca@virginia.edu
- GitHub: [github.com/dnm5ca](https://github.com/dnm5ca)

#### Marieke K Jones, PhD

Marieke is the Research Data Specialist in the Health Sciences Library. She teaches open enrollment workshops in R, consults with researchers about statistics and data analysis, and teaches the BIMS8380 statistics course. Her PhD is in Environmental Science and Policy and she conducted her dissertation research on reproductive physiology and endocrinology.

- Email: marieke@virginia.edu
- GitHub: [github.com/mariekekjones](https://github.com/mariekekjones)